In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4],dtype=float) 

In [ ]:
a # 1 dimensional array

array([1., 2., 3., 4.])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b # 2 dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(4,)

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

In [12]:
b.dtype

dtype('int64')

In [13]:
b.size

6

In [14]:
a.size

4

In [15]:
b.nbytes

48

In [16]:
a.nbytes

32

In [17]:
zeros = np.zeros((3,3))

In [18]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
ones = np.ones((2,4), dtype=int)

In [22]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
identity = np.eye((3), dtype=int)

In [28]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
grid = x.reshape(3,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])